Update user guide
AY2223S1-CS2103T-T08-1/tp pull request #37
Opened 2022-09-30 16:26 UTC by Hoodineee

2022-09-30 16:29 UTC, e1010101 approved these changes
Looks good to merge!

2022-09-30 16:30 UTC, e1010101 requested changes
Re-commit please! There is an issue with CodeCov!

2022-09-30 16:31 UTC, e1010101 approved these changes
Never mind, issue fixed by itself!

2022-10-01 08:33 UTC, xiaoying1129 approved these changes
LGTM

2022-10-01 08:48 UTC, merged